### ISSUE TITLE
IEnumerable<SwFeature> with ForEach

### ISSUE THREAD

**Issue by emersonbottero** [xarial/xcad#10]
Add supporte for 
``` C#
Features.ForEach(feat =>{ 
      //Do something with feat like getting it's type.
});
```

today I have to use like that many times.
``` C#
var Weldment = mPart.Features.First(feat => feat.Name.Contains("Comprimento")) as SwFeature;
```

**Comment by artem1t** [comment]
Features is IEnumerable with deferred execution to maximize the performance.

So in below code features will be traversed only up to 'Comprimento' feature instead of getting all features and then enumerating.

`var Weldment = mPart.Features.First(feat => feat.Name.Contains("Comprimento")) as SwFeature;`

ForEach is an extension of IList (i.e. not deferred type). So you can use the following:

```
Features.ToList().ForEach(feat =>{ 
      //Do something with feat like getting it's type.
});
```
