### ISSUE TITLE
FlatPatternActivator

### ISSUE THREAD

**Issue by fatih1445** [xarial/xcad#105]
FlatPatternActivator not working on multibody sheet metal parts.

![image](https://github.com/xarial/xcad/assets/77345265/699e06ec-f94f-4825-8488-6cd26d750b28)

**Comment by artem1t** [comment]
Could you please attach this sample model?

**Comment by fatih1445** [comment]
[gl_ku007.zip](https://github.com/xarial/xcad/files/13312261/gl_ku007.zip)

**Comment by artem1t** [comment]
Thank you for the sample model. The issue here is that the active configuration of this file is a SM-FLAT-PATTERN and you cannot create flat pattern from the flat pattern configuration. You can try this by trying to create flat pattern of this file manually (there is not flat pattern view).

Just activate your top configuration and it will work. In version 0.8.X there is a better exception for this case

`Xarial.XCad.SolidWorks.Documents.Exceptions.InvalidFlatPatternConfigurationException: 'The flat pattern drawing view is invalid as it does not contain the flat pattern feature in the flattened state. This is usually caused by an invalid SM-FLAT-PATTERN configuration in the part file. Try removing this configuration'
`

**Comment by fatih1445** [comment]
Thank you very much for your time.
